### ISSUE TITLE
Paired data in nyuv2_rectified

### ISSUE THREAD

**Issue by dsshim0125** [JiawangBian/Unsupervised-Indoor-Depth#11]
Hi,

Thank you for your wonderful works.

Is the data has two different sequences?

ex) 00000_0.jpg 000001_0.jpg 000002_0.jpg ....   : seq1
      00000_1.jpg 000001_1.jpg 000002_1.jpg ....   : seq2

do my understanding correct?

Thank you!

**Comment by JiawangBian** [comment]
No. one folder contains one sequence, and many pairs are extracted from one sequence. "000000" stands for the index of the pair. "_0" stands for the first item in one pair, and "_1" stands for the second term in one pair.

**Comment by dsshim0125** [comment]
Thank you for your fast reply!

I have a one additional question.

If so, do I have to train posenet and calculate reprojection loss between 00000_0.jpg and 00000_1.jpg not between 00000_0.jpg and 00001_0jpg?

Thank you!

**Comment by JiawangBian** [comment]
You should train on pair "000000_0, 000000_1" only. 

However, I would like to recommend that you use "sc_depth_pl", where you can train SC-DepthV2 on original sequences directly.

**Comment by dsshim0125** [comment]
I really appreciated your work and reply.

Thanks!
