### ISSUE TITLE
about the scale consistency of rectified_nyu

### ISSUE THREAD

**Issue by Yvaine** [JiawangBian/Unsupervised-Indoor-Depth#6]
Hi,
  If use pair images, the ref_imgs have only one image, so the scale consistency can not guaranteed only by two near image. I wonder if I think is right or not.
Thank you.

**Comment by JiawangBian** [comment]
I think that the consistency can be maintained, because image A would be consistent with image B in a batch, and B would be consistent with C in another batch.

**Comment by Yvaine** [comment]
Thank you.
